import { Link } from '@tanstack/react-router'
import { useState } from 'react'
import { ArrowUpRight, ChevronDown, Clock3, FileText, Mail, MapPin, Menu, MessageCircle, Phone, X, Zap } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { email, phone, trades, tradePaths, whatsapp } from '@/lib/jm-data'

export function Brand() {
 return <Link to="/" className="brand" aria-label="JM Technical Services and Projects home"><span className="brand-mark">JM<span className="brand-bolt"><Zap size={15} fill="currentColor" /></span></span><span className="brand-words">TECHNICAL SERVICES<span>AND PROJECTS</span></span></Link>
}
export function Header() {
 const [open, setOpen] = useState(false)
 return <><div className="emergency-bar"><div className="site-width emergency-inner"><span><Clock3 size={14}/><strong>24/7 CALL-OUTS</strong><span className="emergency-note">Here when you need us.</span></span><div><a href={`mailto:${email}`} className="top-email"><Mail size={14}/>{email}</a><a href="tel:+27832412126"><Phone size={14}/>{phone}</a></div></div></div><header className="main-header"><div className="site-width header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation"><Link to="/" activeOptions={{exact:true}} activeProps={{className:'nav-active'}}>Home</Link><div className="services-menu"><Button variant="nav" className="nav-services">Services<ChevronDown size={13}/></Button><div className="services-dropdown">{trades.map((t,i)=><Link key={t.slug} to={tradePaths[i]!}>{t.name}<ArrowUpRight size={14}/></Link>)}</div></div><Link to="/about">About Us</Link><Link to="/projects">Our Work</Link><Link to="/contact">Contact</Link></nav><Button asChild className="header-quote"><Link to="/quote">Get a Quote<ArrowUpRight/></Link></Button><Button variant="ghost" size="icon" className="mobile-menu-button" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav className="mobile-menu site-width" aria-label="Mobile navigation" onClick={()=>setOpen(false)}><Link to="/">Home</Link>{trades.map((t,i)=><Link key={t.slug} to={tradePaths[i]!}>{t.name}</Link>)}<Link to="/about">About Us</Link><Link to="/projects">Our Work</Link><Link to="/contact">Contact</Link><Link to="/quote">Get a Quote<ArrowUpRight size={16}/></Link></nav>}</header></>
}
export function Footer() {
 return <><footer className="footer"><div className="site-width footer-grid"><div><Brand/><p>One reliable team. Four essential trades.<br/>Technical services that keep Cape Town working.</p><span className="footer-location"><MapPin size={15}/>Cape Town, Western Cape, South Africa</span></div><div><h3>OUR SERVICES</h3>{trades.map((t,i)=><Link key={t.slug} to={tradePaths[i]!}>{t.name}</Link>)}</div><div><h3>QUICK LINKS</h3><Link to="/about">About Us</Link><Link to="/projects">Our Work</Link><Link to="/quote">Request a Quote</Link><Link to="/contact">Contact Us</Link></div><div><h3>LET’S TALK</h3><a href="tel:+27832412126"><Phone size={15}/>{phone}</a><a href={whatsapp()} target="_blank" rel="noreferrer"><MessageCircle size={15}/>WhatsApp Us<ArrowUpRight size={13}/></a><a className="footer-email" href={`mailto:${email}`}>{email}</a><span className="availability"><span/>24/7 call-outs available</span></div></div><div className="site-width footer-bottom"><span>© 2026 JM Technical Services and Projects. All rights reserved.</span><a href="/sitemap.xml">Sitemap<ArrowUpRight size={12}/></a></div></footer><nav className="mobile-contact-bar" aria-label="Quick contact"><a href={whatsapp()} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp Us</a><a href="tel:+27832412126"><Phone/>Call Now</a><Link to="/quote"><FileText/>Request Quote</Link></nav></>
}