import { Link } from '@tanstack/react-router'
import { useState } from 'react'
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Clock3, Hammer, MapPin, MessageCircle, Phone, ShieldCheck, Timer, Wrench, Zap, Droplets, MoveHorizontal } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { areas, faqs, images, trades, tradePaths, whatsapp } from '@/lib/jm-data'
import plumbing from '@/assets/plumbing.jpg'
import welding from '@/assets/welding.jpg'

export const tradeIcons = [Zap, Droplets, Wrench, Hammer]
export const tradeImages = [images.electrical, plumbing, welding, images.house]
export function Eyebrow({children}: {children: React.ReactNode}) { return <div className="eyebrow"><span/>{children}</div> }
export function ContactActions({message, hero=false}: {message?:string, hero?:boolean}) { return <div className="contact-actions"><Button asChild size="lg"><a href={whatsapp(message)} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp Us<ArrowUpRight size={15}/></a></Button><Button asChild size="lg" variant={hero?'hero':'outline'}><a href="tel:+27832412126"><Phone/>Call 083 241 2126</a></Button></div> }
export function TrustStrip() { return <section className="trust-strip"><div className="site-width trust-grid">{[[Timer,'Fast local response','Less waiting. More doing.'],[ShieldCheck,'Quality workmanship','Care in every detail.'],[MapPin,'Cape Town coverage','Your local technical team.'],[FileIcon,'Clear, upfront quotes','Know the scope before we start.']].map(([Icon,title,copy])=>{const I=Icon as typeof Timer;return <div className="trust-item" key={String(title)}><I size={25}/><div><strong>{String(title)}</strong><span>{String(copy)}</span></div></div>})}</div></section> }
function FileIcon({size}: {size?:number}) { return <Check size={size}/> }
export function ServiceCards() { return <div className="service-grid">{trades.map((t,i)=>{const Icon=tradeIcons[i];return <article className="service-card" key={t.slug}><Link to={tradePaths[i]} className="service-image"><img src={tradeImages[i]} alt={`${t.name} workmanship in Cape Town — illustrative image`} loading="lazy" width={1024} height={768}/><span className="service-number">0{i+1}</span></Link><div className="service-card-body"><Icon className="service-icon" size={24}/><h3>{t.name}</h3><p>{t.short}</p><ul>{t.tasks.slice(0,4).map(task=><li key={task}><Check size={13}/>{task}</li>)}</ul><div className="service-card-links"><Link to={tradePaths[i]}>Explore service<ArrowUpRight size={16}/></Link><Link to="/quote" aria-label={`Get a quote for ${t.name}`}><ArrowRight size={18}/></Link></div></div></article>})}</div> }
export function FAQ({compact=false}: {compact?:boolean}) { return <div className="faq-list">{(compact?faqs.slice(0,4):faqs).map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div> }
export function Areas() { const [selected,setSelected]=useState<string|null>(null);return <section className="section area-section"><div className="site-width area-layout"><div><Eyebrow>LOCAL TEAM. LOCAL KNOW-HOW.</Eyebrow><h2>Across Cape Town.<br/>Around the corner.</h2><p>From the city centre to the suburbs, we bring practical technical support to homes and businesses across the Western Cape.</p><span className="area-location"><MapPin size={18}/>Cape Town, Western Cape</span></div><div><div className="area-tags">{areas.map(a=><Button key={a} variant={selected===a?'default':'outline'} onClick={()=>setSelected(a)}>{a}<ArrowUpRight size={14}/></Button>)}</div>{selected&&<div className="area-selection">Need assistance in {selected}? <a href={whatsapp(`Hi JM Technical Services, I need assistance in ${selected}.`)} target="_blank" rel="noreferrer">Talk to our team<ArrowRight size={14}/></a></div>}<p className="area-footnote">Not sure if we cover your area? Give us a call.</p></div></div></section> }
export function FinalCTA() { return <section className="final-cta"><div className="site-width final-layout"><div><Eyebrow>LET’S GET IT SORTED.</Eyebrow><h2>One call. The right team.</h2><p>A repair that can’t wait or a project you’ve been planning?<br/>Tell us what you need. We’ll take it from there.</p></div><div><ContactActions hero/><Link to="/quote" className="text-cta">Prefer to send the details? Request a quote<ArrowRight size={16}/></Link></div></div></section> }
export function Comparison() { const [position,setPosition]=useState(50);return <div className="comparison-wrap"><div className="comparison" style={{'--comparison-position':`${position}%`} as React.CSSProperties}><img className="comparison-after" src={images.after} alt="After: renovated kitchen with charcoal cabinetry, tiled floor and new fittings — concept image" loading="lazy" width={1536} height={1024}/><img className="comparison-before" src={images.before} alt="Before: stripped kitchen with worn cabinets and unfinished floor — concept image" loading="lazy" width={1536} height={1024}/><span className="comparison-label before-label">BEFORE</span><span className="comparison-label after-label">AFTER</span><div className="comparison-divider"><span><MoveHorizontal size={22}/></span></div><input type="range" min="0" max="100" value={position} aria-label="Before and after renovation comparison" onChange={e=>setPosition(Number(e.target.value))}/></div><div className="comparison-caption"><span><strong>A fresh start for every space.</strong> Kitchen renovation</span><span>Concept imagery · not a completed JM project</span></div></div> }
export function Gallery() { const [filter,setFilter]=useState('All work'); const gallery=[{name:'Electrical installations',category:'Electrical',image:images.electrical},{name:'Bathroom plumbing',category:'Plumbing',image:plumbing},{name:'Custom gates & steelwork',category:'Welding',image:welding},{name:'Home improvements',category:'Building',image:images.after}];return <><div className="gallery-filters" role="group" aria-label="Filter work examples">{['All work','Electrical','Plumbing','Welding','Building'].map(f=><Button variant={f===filter?'default':'ghost'} key={f} aria-pressed={f===filter} onClick={()=>setFilter(f)}>{f}</Button>)}</div><div className="gallery-grid">{gallery.filter(g=>filter==='All work'||g.category===filter).map(g=><article key={g.name}><img src={g.image} alt={`${g.name} — illustrative example, not a completed JM project`} loading="lazy" width={1024} height={768}/><div><span>{g.category}</span><h3>{g.name}</h3><Link to="/quote" aria-label={`Enquire about ${g.name}`}><ArrowUpRight size={21}/></Link></div></article>)}</div><p className="image-disclaimer">Illustrative service examples. Real project photographs will be added when available.</p></> }