/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BuildingRouteImport } from './routes/building'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ElectricalRouteImport } from './routes/electrical'
import { Route as PlumbingRouteImport } from './routes/plumbing'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as WeldingRouteImport } from './routes/welding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRoute = BuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalRoute = ElectricalRouteImport.update({
  id: '/electrical',
  path: '/electrical',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingRoute = PlumbingRouteImport.update({
  id: '/plumbing',
  path: '/plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const WeldingRoute = WeldingRouteImport.update({
  id: '/welding',
  path: '/welding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building': typeof BuildingRoute
  '/contact': typeof ContactRoute
  '/electrical': typeof ElectricalRoute
  '/plumbing': typeof PlumbingRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/welding': typeof WeldingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building': typeof BuildingRoute
  '/contact': typeof ContactRoute
  '/electrical': typeof ElectricalRoute
  '/plumbing': typeof PlumbingRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/welding': typeof WeldingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building': typeof BuildingRoute
  '/contact': typeof ContactRoute
  '/electrical': typeof ElectricalRoute
  '/plumbing': typeof PlumbingRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/welding': typeof WeldingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/building'
    | '/contact'
    | '/electrical'
    | '/plumbing'
    | '/projects'
    | '/quote'
    | '/welding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/building'
    | '/contact'
    | '/electrical'
    | '/plumbing'
    | '/projects'
    | '/quote'
    | '/welding'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/building'
    | '/contact'
    | '/electrical'
    | '/plumbing'
    | '/projects'
    | '/quote'
    | '/welding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildingRoute: typeof BuildingRoute
  ContactRoute: typeof ContactRoute
  ElectricalRoute: typeof ElectricalRoute
  PlumbingRoute: typeof PlumbingRoute
  ProjectsRoute: typeof ProjectsRoute
  QuoteRoute: typeof QuoteRoute
  WeldingRoute: typeof WeldingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building': {
      id: '/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof BuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical': {
      id: '/electrical'
      path: '/electrical'
      fullPath: '/electrical'
      preLoaderRoute: typeof ElectricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing': {
      id: '/plumbing'
      path: '/plumbing'
      fullPath: '/plumbing'
      preLoaderRoute: typeof PlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welding': {
      id: '/welding'
      path: '/welding'
      fullPath: '/welding'
      preLoaderRoute: typeof WeldingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildingRoute: BuildingRoute,
  ContactRoute: ContactRoute,
  ElectricalRoute: ElectricalRoute,
  PlumbingRoute: PlumbingRoute,
  ProjectsRoute: ProjectsRoute,
  QuoteRoute: QuoteRoute,
  WeldingRoute: WeldingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
